### PR TITLE
FIX Change namespaces to be unique for this package, fix bug in TestParserExtension and update namespaces in YAML

### LINKED ISSUE #5: Alias master branch
We must alias the master branch so users don't hook to `dev-master` in their requirements.

### PR DESCRIPTION
**Pull request by robbieaverill**
This PR fixes a couple of configuration issues with namespacing, but also changes the namespaces to `SilverStripe\BBCodeParser` from `SilverStripe\View\Parser` - I figure having two autoloaders pointing to different places wouldn't be much help.

Also fixed minor issue in the parser extension in `$this` vs `$this->owner`.

---

Contains PSR-2 formatting as well.

---

* Composer branch alias added - resolves #5

### CODE REVIEW

File: _config.php [hunk 1]
```diff
@@ -0,0 +1,2 @@
+<?php
+define('BBCODEPARSER_PATH', __DIR__);
```
Comment (dhensby) [inline _config.php]: I think the convention is that this would be that this is called `BBCODEPARSER_DIR` - the path would be `BASE_PATH . BBCODEPARSER_DIR`

File: src/BBCodeParser.php [hunk 2]
```diff
@@ -12,143 +12,146 @@
...
 
-		// Get options
-		$config = parse_ini_file('BBCodeParser.ini', true);
-		$options = $config['SSHTMLBBCodeParser'];
+        // Get options
+        $config = parse_ini_file('BBCodeParser.ini', true);
+        $options = $config['SSHTMLBBCodeParser'];
 
-		require_once(__DIR__ . '/../thirdparty/HTML_BBCodeParser2/HTML/BBCodeParser2.php');
+        require_once BBCODEPARSER_PATH . '/thirdparty/HTML_BBCodeParser2/HTML/BBCodeParser2.php';
```
Comment (dhensby) [inline src/BBCodeParser.php]: can we use composer to add this dir to the include path which would save us having to use this constant?

see framework for an example: https://github.com/silverstripe/silverstripe-framework/blob/master/composer.json#L69-L72

File: _config.php (hunk 1 above)
Comment (robbieaverill) [inline _config.php]: If composer can handle the autoloading then this won't be needed anyway

File: src/BBCodeParser.php (hunk 2 above)
Comment (robbieaverill) [inline src/BBCodeParser.php]: Turns out it was already there. Updated!

**Comment by dhensby** [comment]
thanks
